name: Python Tests
run-name: Rest API Python Tests
on:
    schedule:
      - cron: '0 2 * * *'  # Runs daily at midnight UTC
    workflow_dispatch:  # Allows manual triggering of the workflow
      inputs:
        python-version:
          description: 'Python version to use'
          required: true
          default: '3.13.2'
    push:
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set Up Python 3.13.2
        uses: actions/setup-python@v3
        with:
          python-version: "${{ github.event.inputs.python-version || '3.13.2' }}"
      - name: Run Tests
        run: |
             chmod +x -R ${{ github.workspace }}
             pip install --upgrade pip
             pip install -r requirements.txt
             export PYTHONPATH=${PYTHONPATH}:${{ github.workspace }}
             pytest -s tests/part_01/test_users.py --junitxml=results.xml
      - name: Create Test Summary
        uses: test-summary/action@dist
        if: success() || failure()
        with:
          paths: results.xml
